[doh_servers]
direct_servers = [
    "https://doh.pub/dns-query",       # Tencent
    "https://dns.alidns.com/dns-query" # Ali
]
proxy_servers = [
    "https://dns.google/dns-query",   # Google
    "https://1.1.1.1/dns-query",      # Cloudflare
]
bootstrap_server = "223.5.5.5"

[dns]
host = '0.0.0.0'  # Local host '127.0.0.1'
port = 53         # DNS server listening port

[cache]
max_size = 5000000
path = 'dns_cache.json'
save_interval = 72  # hours

[proxy]
enable_proxy = false               # Manual proxy switch proxy.
http = "http://192.168.5.8:7899"   # Use HTTP proxy for DoH requests
https = "http://192.168.5.8:7899"
rule_file = "gfwlist.txt"
rule_file_url = "https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"


[logging]
# log level: DEBUG, INFO, WARNING, ERROR
default_log_level = "INFO"
query_log_level = "INFO"


